config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'my_articles', to: 'articles#my_articles'
  get 'subscripted_article', to: 'articles#subscripted_article'
  resources :articles
  resources :subscriptions, only: [:create, :destroy]
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :subscriptions, dependent: :destroy
  has_many :subscribed_articles, through: :subscriptions, source: :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!
  def new
    @article = Article.new
  end

  def index
    @articles = Article.order(id: :asc)
  end

  def create
    # @article = current_user.articles.new(article_params)
    result = Articles::Create.new(article_params).call

    if result[:success] == true
      redirect_to articles_path
    else
      flash[:alert] = result[:errors]
      render :new
    end

  end

  def show
    @article = Article.find_by(id: params[:id])
  end

  def destroy
    @article = Article.find_by(id: params[:id])

    if @article
      if @article.destroy
        redirect_to articles_path, notice: "Article was successfully deleted."
      else
        flash[:alert] = "Error deleting the article."
        redirect_to articles_path
      end
    else
      flash[:alert] = "Article not found."
      redirect_to articles_path
    end
  end


  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      flash[:alert] = "Article not found."
      render :edit
    end
  end
  def edit
    @article = Article.find_by(id: params[:id])
  end

  def my_articles
    @my_articles = current_user.articles

    if @my_articles.empty?
      flash[:notice] = "You have no articles."
      redirect_to articles_path
    end
  end

  def subscripted_article
    my_subscriptions = current_user.subscriptions
    @articles = Article.where(id: my_subscriptions.pluck(:article_id))

    if @articles.empty?
      flash[:notice] = "You are not subscribed to any articles."
      redirect_to articles_path
    end
  end


  private

  def article_params
    params.require(:article).permit(:title, :entry, :contents, :user_id) # Replace with the actual permitted attributes
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def create
    Subscriptions::Subscribe.new(params,current_user,article).call
    redirect_to article, notice: 'Subscribed to the article.'
  end

  def destroy
    Subscriptions::Unsubscribe.new(params,current_user,subscription,article).call
    redirect_to article, notice: 'Unsubscribed from the article.'
  end

  private

  def subscription
    @subscription ||= current_user.subscriptions.find_by(article_id: params[:article_id])
  end

  def article
    @article ||= Article.find_by(id: params[:article_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_form.html.erb
<div class="flex flex-col">
  <%= form_for @article do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :entry %>
      <%= f.text_area :entry %>
    </div>

    <div class="field">
      <%= f.label :contents %>
      <%= f.text_area :contents %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="actions">
      <%= f.submit 'Update Article',class:"border border-blue-300 p-1 rounded mt-4" %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="flex flex-col">
  <h1>Edit Article</h1>
  <%= render 'form', article: @article %>
  <%= link_to 'Back', articles_path, class:"border border-blue-300 p-1 rounded mt-4" %>
</div>

app/views/articles/index.html.erb
<div class="grid grid-cols">
  <h1>List of Articles</h1>
  <div class="grid grid-cols ml-8 mt-4">
    <% if user_signed_in? %>
      <% @articles.each do |article| %>
        <li><%= link_to article.title, article %></li>
      <% end %>
    <% end %>
  </div>
  <div class="grid grid-rows gap-4 mt-4">
    <% if user_signed_in? %>
      <div class="flex space-x-4">
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete , class: "border border-red-300 p-1 rounded" %>
        <%= link_to "Change Password", edit_user_registration_path , class: "border border-blue-300 p-1 rounded"%>
      </div>
    <% else %>
      <div class="flex space-x-4">
        <%= button_to "Log in", user_session_path , class: "border border-green-300 p-1 rounded"%>
        <%= button_to "Sign In", new_user_registration_path, class: "border border-gray-300 p-1 rounded" %>
      </div>
    <% end %>
  </div>
  <div class="mt-4">
    <%=link_to "Create New Article", new_article_path, class:"border border-gray-300 p-1 rounded mt-4" %>
  </div>

  <div class="mt-4">
    <%=link_to "My Articles", my_articles_path, class:"border border-gray-300 p-1 rounded mt-4" %>
  </div>

  <div class="mt-4">
    <%=link_to "My Subscripted Articles", subscripted_article_path, class:"border border-gray-300 p-1 rounded mt-4" %>
  </div>



  <div class="mt-4">
    <%=current_user.points%>
  </div>

</div>

app/views/articles/my_articles.html.erb
<div class="grid grid-cols">
  <h1>List of My Articles</h1>
  <div class="grid grid-cols ml-8 mt-4">
    <% if user_signed_in? %>
      <% @my_articles.each do |article| %>
        <li><%= link_to article.title, article %></li>
      <% end %>
    <% end %>
  </div>
  <div class="mt-4">
    <%=link_to "Back", articles_path, class:"border border-gray-300 p-1 rounded mt-4" %>
  </div>

</div>

app/views/articles/new.html.erb
<div class="grid grid-cols">
  <h1 class="flex flex-col items-center text-xl">Create a New Article</h1>

  <%= form_for @article do |f| %>
    <div class="field mt-4">
      <div class="flex flex-col items-center">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="field mt-4">
      <div class="flex flex-col items-center">
        <%= f.label :entry %>
        <%= f.text_area :entry %>
      </div>
    </div>

    <div class="field mt-4">
      <div class="flex flex-col items-center">
        <%= f.label :contents %>
        <%= f.text_area :contents %>
      </div>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="flex space-x-4  actions mt-4">
      <%= f.submit 'Create Article', class: " border border-green-300 p-1 rounded" %>
      <%=link_to "Back", articles_path, class:"border border-gray-300 p-1 rounded " %>
    </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="flex flex-col">
  <h1 class="text-4xl"><%= @article.title %></h1>
  <h1 class="text-2xl"><%= @article.entry %></h1>
  <p><%= @article.contents %></p>
  <p><%= @article.user_id %></p>
  <p><%= @article.id %></p>
  <%= link_to "Back to Articles", articles_path, class: "btn btn-primary border border-gray-300 p-1 rounded mt-4" %>


  <% if user_signed_in? %>
    <% if current_user.subscribed_articles.include?(@article) %>
      <%= button_to 'Unsubscribe', subscription_path(article_id: @article.id), method: :delete, class:"border border-red-300 p-1 rounded mt-4" %>

    <% else %>
      <%= button_to 'Subscribe', subscriptions_path(article_id: @article.id), method: :post, class:"border border-red-300 p-1 rounded mt-4" %>
    <% end %>
  <% end %>
  <% if @article.user_id == current_user.id %>
    <%= button_to "Delete Article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class:"border border-red-300 p-1 rounded mt-4"  %>
    <%= link_to "Edit Article", edit_article_path(@article) ,class:"border border-blue-300 p-1 rounded mt-4"  %>
  <% end %>
</div>

app/views/articles/subscripted_article.html.erb
<div class="grid grid-cols">
  <h1>List of Subscripted Articles</h1>
  <div class="grid grid-cols ml-8 mt-4">
    <% if user_signed_in? %>
      <% @articles.each do |article| %>
        <li><%= link_to article.title, article %></li>
      <% end %>
    <% end %>
  </div>
  <div class="mt-4">
    <%=link_to "Back", articles_path, class:"border border-gray-300 p-1 rounded mt-4" %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaukaOdZera</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>


    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>